linters:
  fast: true
  disable-all: true
  enable:
    - unused
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - gosec
    - govet
    - misspell
    - nakedret
    - revive
    - unconvert
    - unparam
    - unused
issues:
  exclude-files:
    - "pkg/git/cloner.go"
