name: "direct-use"
usage: "helm direct-use run"
description: ""
command: "$HELM_PLUGIN_DIR/main"
hooks:
  install: "$HELM_PLUGIN_DIR/install-binary.sh"
  update: "$HELM_PLUGIN_DIR/install-binary.sh"
useTunnel: false
ignoreFlags: false
